In [9]:
import numpy as np


label_map = {'01': 0, '02': 1, '03': 2, '04': 3, '05': 4, '06': 5, '07': 6, '08': 7, '09': 8, '10': 9, 
            '11': 10, '12': 11, '13': 12, '14': 13, '15': 14, '16': 15, '17': 16, '18': 17, '19': 18, '20': 19, 
            '21': 20, '22': 21, '23': 22, '24': 23, '25': 24, '26': 25, '27': 26, '28': 27, '29': 28, '30': 29, 
            '31': 30, '32': 31, '33': 32, '34': 33, '35': 34, '36': 35, '37': 36, '38': 37, '39': 38, '40': 39, 
            '41': 40, '42': 41, '43': 42, '44': 43, '45': 44, '46': 45, '47': 46, '48': 47, '49': 48, '50': 49}

test_labels = np.array([
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10', 
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10', 
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
 '10', '10'])

int_test_labels = np.array([label_map[label] for label in test_labels])

print(label_map['01'])

print(int_test_labels)

0
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [6]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])

x_batch = x[0:10]
x_number = x_batch.shape[0]

print(f'x_batch: {x_batch}')
print(f'x_number: {x_number}')

[1 2 3]


In [5]:
import numpy as np
y_true = np.array([0, 1, 1, 3, 4, 4, 2])
print(np.eye(5)[y_true])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


In [2]:
step_size=1e-0

print(step_size)

print(1e-3)

1.0
0.001


In [7]:
import numpy as np

a = np.array(['a', 'b', 'c'])
b = np.array(['c', 'd', 'e'])

unique_labels = np.unique([a, b])

for idx, label in enumerate(unique_labels):
    print(f'idx: {idx}, label: {label}')

label_map = {label: idx for idx, label in enumerate(unique_labels)}

print(label_map)
print(label_map['a'])

int_a_labels = np.array([label_map[label] for label in a])
int_b_labels = np.array([label_map[label] for label in b])

print(f'int_a_labels: {int_a_labels}')
print(f'int_b_labels: {int_b_labels}')

idx: 0, label: a
idx: 1, label: b
idx: 2, label: c
idx: 3, label: d
idx: 4, label: e
{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}
0
int_a_labels: [0 1 2]
int_b_labels: [2 3 4]
